import { defineConfig } from "vite";
import preact from "@preact/preset-vite";
import path from "path";
import fs from "fs";

const screensDir = path.resolve(__dirname, "src/Screens");

/**
 * Returns the names of all directories within a parent folder.
 *
 * @param {string} parent Directory to search.
 * @returns {string[]} Names of the directories within the parent folder.
 */
const getDirectories = (parent) => {
  return fs.readdirSync(parent).filter((file) => {
    return fs.statSync(path.join(parent, file)).isDirectory();
  });
};

/**
 * Creates a Vite virtual module that exports every screen found in `src/Screens`.
 *
 * For example, if the directory contains:
 *
 *   src/Screens/
 *     Scoreboard/
 *     HeadToHead/
 *     Casters/
 *
 * The virtual module will effectively contain:
 *
 *   export { Scoreboard } from "@Screens/Scoreboard";
 *   export { HeadToHead } from "@Screens/HeadToHead";
 *   export { Casters } from "@Screens/Casters";
 *
 * This allows application code to import all screen from a single module without
 * having to manually maintain an index file.
 *
 * This module is wired into Vite's file watcher so adding, removing, or changing
 * screen directories causes the virtual module to be regenerated during
 * development.
 *
 * @returns {import("vite").Plugin} Vite plugin definition.
 */
const ScreenVirtualModule = () => {
  return {
    name: "jonch-screen-virtual-index",

    /**
     * Called when Vite starts a build or development server.
     *
     * Register the Screens directory and each existing screen directory with
     * Vite's watcher so changes to them can invalidate the virtual module.
     *
     */
    buildStart() {
      // Watch the Screen directory so adding/removing a screen can be detected
      this.addWatchFile(screensDir);

      // Watch each individual screen directory for changes
      for (const screen of getDirectories(screensDir)) {
        this.addWatchFile(path.join(screensDir, screen));
      }
    },

    /**
     * Called by Vite when a watched file changes.
     *
     * If the changed file belongs to Screen, invalidate the virtual module so
     * Vite will call `load()` again and rebuild its exports.
     *
     * @param {string} file Absolute path of the changed file
     */
    watchChange(file) {
      if (file.startsWith(path.resolve(__dirname, "src/Screens"))) {
        this.invalidate("virtual:screens");
      }
    },

    /**
     * Resolves the virtual module's import ID.
     *
     * `virtual:screen` does not exist as a physical file. This tells Vite
     * that our plugin owns the module ID.
     *
     * @param {string} id Module ID being resolved.
     * @returns {string|undefined} The virtual module ID when matched.
     */
    resolveId(id) {
      if (id === "virtual:screens") return id;
    },

    /**
     * Generates the contents of the virtual module.
     *
     * The generated module is not written to disk. Vite receives this string
     * as though it were the contents of a real JS file.
     *
     * @param {string} id Module ID being loaded
     * @returns {string|undefined} Generated module source.
     */
    load(id) {
      if (id !== "virtual:screens") {
        return;
      }

      const lines = getDirectories(screensDir).map((name) => {
        return `export { ${name} } from "@Screens/${name}"`;
      });

      return lines.join("\n");
    },
  };
};

/**
 * Creates a Vite plugin that generates one HTML entry point per screen.
 *
 * Vite normally produces `index.html` as the application's HTML entry.
 * This plugin takes that generated HTML and creates additional files:
 *
 *   index.html
 *   Scoreboard.html
 *   HeadToHead.html
 *   Casters.html
 *
 * Each generated HTML file is identical to the original except that the
 * root application element receives a `data-screen` attribute identifying
 * the screen it belongs to.
 *
 * For example:
 *
 *   <div id="app">
 *
 * becomes:
 *
 *   <div id="app" data-screen="Scoreboard">
 *
 * This allows the same entry point to determine which screen should be
 * displayed based on the HTML file that loaded it.
 *
 * @returns {import("vite").Plugin} Vite plugin definition.
 */
const ScreenHTMLGenerator = () => {
  return {
    name: "jonch-screen-html-generator",
    enforce: "post",
    apply: "build",

    /**
     * Called after Vite has generated the final bundle.
     *
     * Finds the generated index.html, creates a copy for every screen, adds
     * that screen's `data-screen` attribute to #app, and emits the result
     * as a separate HTML asset.
     *
     * @param {object} _ Rollup output options. Unused.
     * @param {import("rollup").OutputBundle} bundle Generated bundle.
     * @returns
     */
    generateBundle(_, bundle) {
      // Find the HTML entry generated by Vite
      const indexEntry = Object.entries(bundle).find(([filename]) => filename === "index.html");

      if (!indexEntry) {
        this.error("No HTML file found in bundle");
        return;
      }

      const [, index] = indexEntry;

      const results = [];

      for (const screen of getDirectories(screensDir)) {
        /**
         * Create a copy of index.html with the screen name attached
         * to the application's root element.
         *
         * The regex specifically looks for the below shape and
         * preserves any other attributes already present.
         *
         *   <div ... id="app" ...>
         */
        const source = index.source.replace(
          /<div([^>]*?)\s(id=["']app["'])([^>]*)>/i,
          (_, before, idAttr, after) => {
            // Remove an existing data-screen attribute so this plugin doesn't accidentally duplicate it
            const cleanAttrs = `${before} ${idAttr} ${after}`.replace(
              /\s*data-screen=["'][^"']*["']/i,
              "",
            );

            return `<div${cleanAttrs}data-screen="${screen}">`;
          },
        );

        // Each screen gets its own HTML entry point.
        const fileName = `${screen}.html`;

        this.emitFile({
          type: "asset",
          fileName,
          source,
        });

        results.push({
          Screen: screen,
          File: fileName,
          Status: "✅ Emitted",
        });
      }

      // Print a useful summary after the build.
      if (results.length > 0) {
        console.log("\n Screens Generated.");
        console.table(results);
      }
    },
  };
};

export default defineConfig({
  base: "./",
  build: {
    outDir: "../build",
    emptyOutDir: true,
  },
  plugins: [preact(), ScreenVirtualModule(), ScreenHTMLGenerator()],
  root: "./src",
  resolve: {
    alias: {
      "@Assets": path.resolve(__dirname, "./src/Assets"),
      "@Components": path.resolve(__dirname, "./src/Components"),
      "@Screens": path.resolve(__dirname, "./src/Screens"),
      "@Utils": path.resolve(__dirname, "./src/Utils"),
    },
  },
});
